### ISSUE TITLE
Breaking changes in `indent-blankline` v3

### ISSUE THREAD

**Issue by aspeth** [TheGLander/indent-rainbowline.nvim#1]
Thanks so much for this plugin, I've been loving it!

I updated my `indent-blankline` to v3 and it seems to be incompatible, but haven't had time to take a look at the breaking changes to see if I could put up a PR to fix it, but wanted to at least write this here for anyone else who runs into this.

https://github.com/lukas-reineke/indent-blankline.nvim/wiki/Migrate-to-version-3

**Comment by fuchami** [comment]
I too find this plugin useful.
Do you have any plans to modify it for compatibility?

**Comment by shun-li-casia** [comment]
same problem

**Comment by TheGLander** [comment]
Hey everyone, I'm gladly surprised to hear that there are people actually using this thing! I mostly made this repository so that it could be used in package managers easily, but I'm happy to find out that other people find it useful!

Anyways, I've actually adapted rainbowline to work with IBLv3 a bit ago (when I first saw this issue), but since I couldn't use IBLv3 in my config then, I didn't push the changes to GitHub. I've done so now, so you should just be able to update it like any other package and it should work fine. Again, very happy to hear that there are people using this, thank you!!
